### ISSUE TITLE
MAGPIE_ADMIN_PASSWORD reset to default "qwerty" after go-live

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/Magpie#230] opened 2019-11-11 20:54 UTC
See PR https://github.com/Ouranosinc/PAVICS/pull/149

Upgrade from `magpie:0.4.5` to `magpie:1.7.0`.

The value of `MAGPIE_ADMIN_PASSWORD` in `env.local` is reset to default value `qwerty`.

Tons of these errors in magpie logs:
```
[2019-11-11 19:38:19,088] ERROR      [ThreadPoolExecutor-0_0][magpie.utils] Exception during request: [POST pavics.ouranos.ca:443 /magpie/signin_internal]
Traceback (most recent call last):
  File "/opt/local/src/magpie/magpie/utils.py", line 319, in log_exc
    return handler(request)
  File "/opt/local/src/magpie/magpie/api/generic.py", line 101, in validate_accept_header
    return handler(request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.7/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
    response = view(request)
  File "/opt/local/src/magpie/magpie/api/login/login.py", line 134, in login_failure
    ax.raise_http(httpError=http_err, content=content, detail=s.Signin_POST_UnauthorizedResponseSchema.description)
  File "/opt/local/src/magpie/magpie/api/exception.py", line 318, in raise_http
    raise resp
pyramid.httpexceptions.HTTPInternalServerError: The server has either erred or is incapable of performing the requested operation.
```

Twitcher logs:
```
2019-11-11 19:28:40,846 ERROR [TWITCHER:33][waitress] unknown error
Traceback (most recent call last):
  File "/opt/birdhouse/src/twitcher/twitcher/tweens.py", line 27, in ows_security_tween
    security.check_request(request)
  File "/opt/local/src/magpie/magpie/adapter/magpieowssecurity.py", line 41, in check_request
    httpError=HTTPForbidden, msgOnFail="Service query by name refused by db.")
  File "/opt/local/src/magpie/magpie/api/exception.py", line 237, in evaluate_call
    contentType=contentType)
  File "/opt/local/src/magpie/magpie/api/exception.py", line 318, in raise_http
    raise resp
pyramid.httpexceptions.HTTPForbidden: Access was denied to this resource.
```

Work-around was to edit `env.local` to set `MAGPIE_ADMIN_PASSWORD` to the default value `qwerty` and restart both containers `twitcher` and `magpie`.

**Comment by tlvu** [comment] 2019-11-11 20:57
We never caught this earlier since all dev and staging servers are simply using default values without ever changing them like prod system.  We should avoid doing this going forward.

**Comment by fmigneault** [comment] 2019-11-11 21:41
Relates to #231 
Most probably the password is not reset, as there isn't any such operation in Magpie.
Magpie creates a 'second' admin using the default username as it could not find an explicit value defining the existing admin.

**Comment by tlvu** [comment] 2019-11-11 21:52
If we delete the 2nd admin user, will it make the original admin user active again?  And we could have 2 users with the same `admin` username?  Should this be forbidden?  Sounds like a honeypot for error.

**Comment by davidcaron** [comment] 2019-11-11 21:59
- User names are unique in the database
- If you configure another admin username, the other one is still connectable
- If the admin username given in the configuration exists, no admin user is created, no matter what the password is in the configuration or in the database

**Comment by davidcaron** [comment] 2019-11-11 22:20
I think I found the issue... it's in this migration: https://github.com/Ouranosinc/Magpie/blob/master/magpie/alembic/versions/2a6c63397399_separate_personal_standard_groups.py

This line deletes the admin user: https://github.com/Ouranosinc/Magpie/blob/838d39270177bdebc446f2ca38bb3ab1ad5ff20f/magpie/alembic/versions/2a6c63397399_separate_personal_standard_groups.py#L97

And this one recreates it with default values: https://github.com/Ouranosinc/Magpie/blob/838d39270177bdebc446f2ca38bb3ab1ad5ff20f/magpie/alembic/versions/2a6c63397399_separate_personal_standard_groups.py#L173

I'm not 100% sure, but it really looks like it's what is happening here.

**Comment by fmigneault** [comment] 2019-11-12 19:31
Indeed. I think `admin` was an hardcoded value at that time, then came in the configuration value that allows us to set one as desired, which cause problems now.

Maybe this migration step could attempt to ignore some key users such as admin/administrator.
The idea of the step was that before, a `group` "my-user" was *always* created when adding a `user` "my-user". 

Technically (or rather the way it is intended to be), a `user` "admin" should never have direct permissions as they should be applied on the `group` "administrators", and the "admin" user inherits the permissions from that group. This admin `user` is only to allow first login as someone that has "administrators" permissions to setup configurations.
Relates to `read-only` part of #47.

Maybe we can add a migration step just before that one to move the permissions from admin user => admin group. Admin users created afterwards (regardless of the configured env), should inherit the permissions from the group membership. 

Opinions?

**Comment by davidcaron** [comment] 2019-11-12 19:50
FYI, I could recreate the bug to confirm: 
- recreate an empty database for magpie
- checkout pavics at the commit just before merging the magpie/twitcher update (v0.4.5)
- run magpie, change the admin password
- update magpie to v0.5.0, and run the migrations
- try to login with the changed password and the default password

@fmigneault I'll let you decide whether the fix is necessary, a quick fix for this migration would be to insert the hashed password of the old admin user into the new admin user's password column. I think most deployments will not use this migration now that they're updated...

**Comment by fmigneault** [comment] 2019-11-12 22:30
@davidcaron 
The problem is that I don't think we want to rename the admin user as this value could be changed anytime. Technically, we don't actually care what the default admin name is as permissions should be applied to him directly as per #47. 
If all permissions are applied on the group, the new and old admin users should both get all the access transparently. 

So I think its more a problem of permissions that where previously applied incorrectly to the user instead of the admin group because #47 is not yet enforced.

We will still get the same error if, for example, the admin name was again changed between your steps 4-5 after rebooting magpie.

**Comment by tlvu** [comment] 2019-11-18 17:56
Until this bug is fixed, as a work-around, can I set a more secure magpie admin pasword or the password will be reset again on next magpie upgrade?

**Comment by davidcaron** [comment] 2019-11-18 18:12
@tlvu yes you can change the password. It will not be changed again in the next update, as the problem came from a migration that won't be ran again.

**Comment by tlvu** [comment] 2019-11-18 19:26
Done, thanks for the confirmation, Pavics was wide open on the internet with the default password.

**Comment by fmigneault** [comment] 2021-04-08 22:59
Closing due to inactivity. 
Should be handled with password checked for diff before update in #408

**Closed by fmigneault** 2021-04-08 22:59 UTC
Labels: bug, investigate
